#!/usr/bin/php

<?php

use infuse\Util;

require_once 'vendor/autoload.php';
require_once 'assets/constants.php';

define( 'INFUSE_BASE_DIR', dirname( __DIR__ ) );

function app()
{
	$config = @include 'config.php';
	$config[ 'modules' ][ 'middleware' ] = [];
	$config[ 'sessions' ][ 'enabled' ] = false;
	$config[ 'logger' ][ 'enabled' ] = false;
	return new App( $config );
}

$args = $argv;
unset( $args[ 0 ] );

$command = Util::array_value( $args, 1 );
if( $command == "migrate" )
	return (int)!app()->installSchema( Util::array_value( $args, 2 ), true );
else if( $command == "test" )
{
	unset( $args[ 1 ] );
	if( isset( $args[ 2 ] ) )
		$args[ 2 ] = 'app/' . $args[ 2 ] . '/tests/';
	system( 'phpunit ' . implode( ' ', $args ) );
}
else
{
	$args = $argv;
	unset( $args[ 0 ] );

	system( "php public/index.php " . implode( ' ', $args ) );
}